vars = c( "log_diff_head",
          "diff_head",
          "condition",
          "cross.wind",
          "dist2cent",
          "dist2home",
          "turn2falchead",
          "dir.rel.ali",
          "unique.flight",
          "turn2falcpos",
          "align",
          "attract",
          "small.big",
          "turn2home",
          "pigeon",
          "Date",
          "group.num")
